config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'trips#index'
  resources :trips do
    resources :locations 
  end
  resources :locations do
  resources :addresses 
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :location

  validates :street, :city, :state, :zip, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_many :addresses, dependent: :destroy

  validates :name, :days, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :locations, dependent: :destroy

  validates :name, :start_date, :end_date, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  before_action :set_location
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  def index
    @addresses = @location.addresses
  end

  def show
  end

  def new
    @address = @location.addresses.new
  end

  def create
    @address = @location.addresses.new(address_params)
    if @address.save
      redirect_to location_addresses_path(@location)
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @address.update(address_params)
      redirect_to location_addresses_path(@location)
    else
      render :edit
    end
  end
  def destroy

    @address.destroy
    redirect_to location_addresses_path(@location)
  end
  private
    def set_location
      @location = Location.find(params[:location_id])
    end
    def set_address
      @address = @location.addresses.find(params[:id])
    end
    def address_params
      params.require(:address).permit(:street, :city, :state, :zip, :location_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :set_trip
    before_action :set_location, only: [:show, :edit, :update, :destroy]
    
    def index
      @locations = @trip.locations
    end
  
    def show
      
    end
  
    def new
      @location = @trip.locations.new
    end
  
    def create
      @location = @trip.locations.new(location_params)
      if @location.save
        redirect_to trip_locations_path(@trip)
      else
        render :new
      end
    end
  
    def edit
      
    end
  
    def update
      if @location.update(location_params)
        redirect_to trip_location_path(@trip, @location)
      else
        render :edit
      end
    end
  
    def destroy
      @location.destroy
      redirect_to trip_locations_path(@trip)
    end
  
    private
    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_location
      @location = @trip.locations.find(params[:id])
    end
  
    def location_params
      params.require(:location).permit(:name, :days, :trip_id)
    end
  
  
  end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all.order("name")

  end

  def show
  end

  def new
    @trip = Trip.new
    
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to @trip
    else
      render :new
    end
  end

  def edit
    
  end


  def update
    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end

  private
  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name, :start_date, :end_date)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/addresses/_form.html.erb
<h1><%= @address.id ? 'Edit Address' : 'Create Address' %></h1>
<div class="ui form">

    <%= form_for [@location, @address] do |l| %>
      <%= l.label :street %>
      <%= l.text_field :street, required: true %>
      <br><br>

      <%= l.label :city %>
      <%= l.text_field :city, required: true %>

      <%= l.label :state %>
      <%= l.text_field :state, required: true %>

      <%= l.label :zip %>
      <%= l.text_field :zip, required: true %>

      <br><br>

      <%= l.submit %>
      <br><br>

</div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Address</h1>
<!-- form_with(model: @location, @address, local: true, class: 'form') -->
<div class="ui form">
 <%= form_for [@location, @address] do |f| %>
   <%= f.label :street %>
   <%= f.text_field :street %>
   <br><br>
   <%= f.label :city %>
   <%= f.text_field :city %>
   <br><br>
   <%= f.label :state %>
   <%= f.text_field :state %>
   <br><br>
   <%= f.label :zip %>
   <%= f.number_field :zip %>
   <br><br>
   <br><br>
   <div><button class="btn btn-warning"> <%= f.submit %></button></div>
   
   <button class="btn btn-success"> <%= link_to 'Back', root_path%> </button>
   <br><br>
 <% end %>
</div>

app/views/addresses/index.html.erb
<h1 class='ui header'><%= @location.name %> Address</h1>
<% if @addresses == [] %>
<%= link_to 'Add Address', new_location_address_path(@location) %>
<% else %>
<ul>
<%= @addresses.each do |address| %>
  <li>Street Name: <%=address.street%></li>
  <li>City: <%=address.city%></li>
  <li>State: <%=address.state%></li>
  <li>Zip: <%=address.zip%></li>
  <li><%= link_to "Delete", location_address_path(@location, address.id), method: :delete%></li>
  <li><%= link_to "Edit", edit_location_address_path(@location, address.id)%></li>
  </ul>
  <br>
  <br>
<% end %>
<% end %>

app/views/addresses/new.html.erb
<h1>Add Address</h1>


<div class="ui form">
<%= form_for [@location, @address] do |a| %>
  <div class="field">
  <%= a.label :street %>
  <%= a.text_field :street, required: true %>
  </div>
  <div class="field">
  <%= a.label :city %>
  <%= a.text_field :city, required: true %>
  </div>
  <div class="field">
  <%= a.label :state %>
  <%= a.text_field :state, required: true %>
  </div>
  <div class="field">
  <%= a.label :zip %>
  <%= a.text_field :zip, required: true %>
  </div>


  <%= a.submit %>

  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="ui secondary  menu">
  <div class="item">
    <%= link_to "Trips", root_path %>
  </div>
  <div class="item">
    <%= link_to "Add a trip", new_trip_path %>
  </div>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
    <a class="ui item">
      Logout
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
  <div class = 'ui container top'>
    <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= @song.id ? 'Edit Location' : 'Create Location' %></h1>
<div class="ui form">

    <%= form_for [@trip, @location] do |l| %>
      <%= l.label :name %>
      <%= l.text_field :name, required: true %>
      <br><br>

      <%= l.label :days %>
      <%= l.text_field :days, required: true %>
      <br><br>

      <%= l.submit %>
      <br><br>

</div>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>
<!-- form_with(model: @trip, local: true, class: 'form') -->
<div class="ui form">
 <%= form_for [@trip, @location] do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>
   <br><br>
   <%= f.label :days %>
   <%= f.number_field :days %>
   <br><br>
   <br><br>
   <div><button class="btn btn-warning"> <%= f.submit %></button></div>
   
   <button class="btn btn-success"> <%= link_to 'Back', root_path%> </button>
   <br><br>
 <% end %>
</div>

app/views/locations/index.html.erb
<h1>
  Locations
</h1>
<br>
<% if @locations == [] %>
<%= link_to "Add New Location", new_trip_location_path(@trip) %>
<% else %>
<div class="ui raised very padded text container segment">
<div class="ui list">
  <table class="table">
  <thead>
  <tr class="">
  <th>State</th>
  <th>Start Date</th>
  <th>Days</th>
  <th>Show</th>
  <th>Edit</th>
  <th>Delete</th>
  </tr>
</thead>
  <% @locations.each do |location| %>
  <tr>
    <td class="item"><%= location.name %></td>
  <td class="item"><%= @trip.start_date.strftime("%m-%d-%y") %></td>
  <td class="item"><%= location.days %></td>
  <td><%= link_to "Address", location_addresses_path(location.id)%></td>
  <td><%= link_to "Edit ", edit_trip_location_path(@trip, location.id)%></td>
  <td><%= link_to "Delete", trip_location_path(@trip, location.id), method: :delete %></td>
  <% end %>
  </tr>
  </table>
</div>
</div>

<%= link_to "Add New Location", new_trip_location_path(@trip) %>
<% end %>

app/views/locations/new.html.erb
<h1>Add a Location</h1>

<!-- form_with(model: @location, local: true, class: 'form') -->
<div class="ui form">

    <%= form_for [@trip, @location] do |l| %>
      <%= l.label :name %>
      <%= l.text_field :name, required: true %>
      <br><br>

      <%= l.label :days %>
      <%= l.text_field :days, required: true %>
      <br><br>

      <%= l.submit %>
      <br><br>

</div>
<% end %>

app/views/locations/show.html.erb
<h1>Location</h1>

<br>
<div class="ui raised very padded text container segment">
<h2 class='ui header'><%= @location.name %></h2>
<p>Length: <%=@location.days %></p>
<br>
<% if @location.addresses == [] %>
<%= link_to 'Add New Address', new_location_address_path(@location) %>
<br>
<% else %>
<%= link_to 'Show: Address', location_addresses_path(@location) %>
<% end %>


</div>


<%= link_to "Back", trip_location_path(@trip, @location)%>

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>
<!-- form_with(model: @trip, local: true, class: 'form') -->
<div class="ui form">
 <%= form_for @trip do |f| %>
    <%= f.label :name %>
    <%= f.text_field(:name) %>


    <%= f.label :start_date %>
    <%= f.date_field :start_date, required: true %>
    

    <%= f.label :end_date %>
    <%= f.date_field :end_date, required: true %>
  
   
   <button class="btn btn-success"> <%= link_to 'Back', root_path%> </button>
   <button class="btn btn-warning"> <%= f.submit %> </button>

 <% end %>
</div>

app/views/trips/index.html.erb
<h1 class="ui center aligned icon header">
  <i class="circular plane icon"></i>
  Trips
</h1>
<br>
<div class="ui raised very padded text container segment">
<div class="ui list">
  <% @trips.each do |trip| %>
    <div class="item"><%= link_to trip.name, trip %></div>
  <% end %>
</div>
</div>

app/views/trips/new.html.erb
<h1>Trip</h1>

<!-- form_with(model: @trip, local: true, class: 'form') -->
<div class="ui form">
  <%= form_for @trip do |f| %>
    <%= f.label :name %>
    <%= f.text_field(:name) %>
    <br><br>

    <%= f.label :start_date %>
    <%= f.date_field :start_date, required: true %>
    <br><br>

    <%= f.label :end_date %>
    <%= f.date_field :end_date, required: true %>
  <br>
<%= f.submit %>
<br><br>
<%= link_to 'Back', root_path %></div>
    <br><br>
  <% end %>
</div>

app/views/trips/show.html.erb
<h1>Trip</h1>
<br>
<div class="ui raised very padded text container segment">
<h2 class='ui header'><%= @trip.name %></h2>
<ul>
 <li>
   Start Date: <%=@trip.start_date %>
 </li>
 <li>
   End Date: <%=@trip.end_date %>
 </li>
</ul>
<br>
<%= link_to 'Add New Location', new_trip_location_path(@trip) %>
<br>
<%= link_to 'Locations', trip_locations_path(@trip) %>
</div>
<%= link_to 'Edit Trip', edit_trip_path(@trip) %>
<br>
<%= button_to 'Delete Trip', trip_path(@trip), method: :delete %>